import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";

export default function Home({ exploreData, cardsData }: any) {
  return (
    <>
      <div className="min-h-screen bg-white-50">
        <Head>
          <title>Airbnb Clone</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* header */}
        <Header />

        {/* banner */}
        <Banner />

        {/* content */}
        <main className=" max-w-7xl mx-auto px-8 sm:px-16">
          <section className="pt-5">
            <h2 className="text-2xl font-semibold pb-5 ">Explore Nearby</h2>

            {/* Pull ssome data from server */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {exploreData?.map((item: any) => (
                <SmallCard
                  key={item.img}
                  img={item.img}
                  distance={item.distance}
                  location={item.location}
                />
              ))}
            </div>
          </section>
          <section className="pt-5">
            <h2 className="text-2xl font-semibold pb-5 ">Live Anywhere</h2>

            {/* Pull ssome data from server */}
            <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
              {cardsData?.map((item: any) => (
                <MediumCard key={item.img} img={item.img} title={item.title} />
              ))}
            </div>
          </section>
          <section className="pt-5">
            <LargeCard
              img="https://links.papareact.com/4cj"
              title="The Gratest Outdoors"
              description="Wishlist created by Airbnb."
              buttonText="Get Inspired"
            />
          </section>
        </main>

        {/* footer */}
        <Footer />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );

  const cardsData = await fetch("https://www.jsonkeeper.com/b/19N2").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
